### ISSUE TITLE
Control TextBox

### ISSUE THREAD

**Issue by Rosa218** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Rosa218#2]
[TextBox(Reporte).pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Rosa218/files/6399992/TextBox.Reporte.pdf)

**Comment by MariaC232** [comment]
Buen trabajo
Calificación: 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
